//User Actions
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USER_MODEL = 'LOAD_USER_MODEL';
export const LOAD_USER_LOGIN_SUCCESS = 'LOAD_USER_LOGIN_SUCCESS';


//Company Actions
export const LOAD_COMPANY_MODEL = 'LOAD_COMPANY_MODEL';